project_id = "qbjuomsmnrclsjhdsjcz"

[functions.publish-coach]
verify_jwt = false

[functions.resolve-onboarding-link]
verify_jwt = false

[functions.create-onboarding-link]
verify_jwt = false

[functions.toggle-featured-coach]
verify_jwt = false
