// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = https://qbjuomsmnrclsjhdsjcz.supabase.co;
const SUPABASE_PUBLISHABLE_KEY =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFianVvbXNtbnJjbHNqaGRzamN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5NzU3NzEsImV4cCI6MjA4NzU1MTc3MX0.oFw5D8DsnwbObCfZq6hn7TPLE5Wx9fS0-8WablLT2RA;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});